#pragma kernel CSMain

RWTexture2D<float4> Result;

struct Point
{
    int x;
    int y;
    int OnCurve;
};

StructuredBuffer<Point> _Points;
int _PointsCount;

StructuredBuffer<int> ContourEndIndices;
int _IndicesCount;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    // TODO: insert actual code here!

    Result[id.xy] = float4(id.x & id.y, (id.x & 15)/15.0, (id.y & 15)/15.0, 0.0);
}
